---
abstract: 'RT REST Extension'
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-REST
no_index:
  directory:
    - inc
requires:
  Encode: 0
  JSON: 0
  Moose: 0
  MooseX::NonMoose: 0
  Plack::Builder: 0
  Scalar::Util: 0
  UNIVERSAL::require: 0
  Web::Machine: 0
  namespace::autoclean: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
